version: "3.1"
services:
  bullmq-redis:
    image: redis:alpine
    restart: always
    ports:
      - 6379:6379
    volumes:
      - "./docker/redis/redis-data:/var/lib/redis"
      - "./docker/redis:/usr/local/etc/redis/redis.conf"
